"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Development settings - DO NOT USE THIS IN PRODUCTION
from myproject.settings import *

SECRET_KEY = 'jtn(8qrh9l5(8ows!h-kcqb=^ds&y8s!4!cd0wn#v712q7l=5t'

DEBUG = True

ALLOWED_HOSTS = ['*']


